ARG BASE_IMAGE=ice-ii/fedora-clang-libcxx:v2
FROM ${BASE_IMAGE}

USER root

RUN dnf install -y \
        boost-devel \
        libarchive-devel \
        libcap-ng-devel \
        libzstd-devel \
        lzo-devel \
        pkgconf-pkg-config \
        xxhash-devel \
    && test "$(sed -n 's/^#define BOOST_VERSION //p' /usr/include/boost/version.hpp)" -ge 107400 \
    && pkg-config --atleast-version=0.8.0 libxxhash \
    && pkg-config --atleast-version=1.4.0 libzstd \
    && dnf clean all

LABEL org.icecream.farm.p50-dependencies="boost-xxhash-zstd-lzo-archive-cap-ng"
