#define ZSTD_STATIC_LINKING_ONLY
#include <zstd.h>
#include <zlib.h>

#include <dlfcn.h>

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <limits>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <vector>

namespace {

using Bytes = std::vector<uint8_t>;
using Clock = std::chrono::steady_clock;

struct Blob {
    std::string name;
    size_t file_index = 0;
    Bytes deflated;
    Bytes inflated;
};

struct Corpus {
    std::vector<std::string> files;
    std::vector<uint64_t> file_bytes;
    std::vector<Blob> blobs;
    uint64_t deflated_bytes = 0;
    uint64_t inflated_bytes = 0;
};

struct ZstdResult {
    Bytes wire;
    double seconds = 0.0;
};

struct libdeflate_compressor;

class LibdeflateApi {
public:
    using Alloc = libdeflate_compressor *(*)(int);
    using Bound = size_t (*)(libdeflate_compressor *, size_t);
    using Compress = size_t (*)(libdeflate_compressor *, const void *, size_t, void *, size_t);
    using Free = void (*)(libdeflate_compressor *);

    LibdeflateApi() {
        handle_ = dlopen("libdeflate.so.0", RTLD_LAZY | RTLD_LOCAL);
        if (!handle_) {
            return;
        }
        alloc = symbol<Alloc>("libdeflate_alloc_compressor");
        bound = symbol<Bound>("libdeflate_zlib_compress_bound");
        compress = symbol<Compress>("libdeflate_zlib_compress");
        free = symbol<Free>("libdeflate_free_compressor");
        if (!alloc || !bound || !compress || !free) {
            dlclose(handle_);
            handle_ = nullptr;
        }
    }

    ~LibdeflateApi() {
        if (handle_) {
            dlclose(handle_);
        }
    }

    LibdeflateApi(const LibdeflateApi &) = delete;
    LibdeflateApi &operator=(const LibdeflateApi &) = delete;

    explicit operator bool() const { return handle_ != nullptr; }

    Alloc alloc = nullptr;
    Bound bound = nullptr;
    Compress compress = nullptr;
    Free free = nullptr;

private:
    template <typename Function>
    Function symbol(const char *name) {
        return reinterpret_cast<Function>(dlsym(handle_, name));
    }

    void *handle_ = nullptr;
};

[[noreturn]] void fail(const std::string &message) {
    throw std::runtime_error(message);
}

size_t checked_zstd(size_t code, const char *operation) {
    if (ZSTD_isError(code)) {
        fail(std::string(operation) + ": " + ZSTD_getErrorName(code));
    }
    return code;
}

uint64_t parse_u64(const char *text, const char *option) {
    errno = 0;
    char *end = nullptr;
    const unsigned long long value = std::strtoull(text, &end, 10);
    if (errno || end == text || *end != '\0') {
        fail(std::string("bad ") + option + ": " + text);
    }
    return static_cast<uint64_t>(value);
}

int parse_int(const char *text, const char *option) {
    const uint64_t value = parse_u64(text, option);
    if (value > static_cast<uint64_t>(std::numeric_limits<int>::max())) {
        fail(std::string("out-of-range ") + option + ": " + text);
    }
    return static_cast<int>(value);
}

void parse_values(const std::string &line, size_t begin, size_t end, Bytes &out,
                  const std::string &path, size_t line_number) {
    size_t at = begin;
    while (at < end) {
        while (at < end && (line[at] == ' ' || line[at] == '\t' || line[at] == ',' ||
                            line[at] == '\r' || line[at] == '\n')) {
            ++at;
        }
        if (at == end) {
            break;
        }
        int base = 10;
        if (at + 2 <= end && line[at] == '0' &&
            (line[at + 1] == 'x' || line[at + 1] == 'X')) {
            base = 16;
        }
        const char *first = line.data() + at;
        char *last = nullptr;
        errno = 0;
        const unsigned long value = std::strtoul(first, &last, base);
        if (errno || last == first || value > 255 || last > line.data() + end) {
            fail(path + ":" + std::to_string(line_number) +
                 ": malformed generated byte array");
        }
        out.push_back(static_cast<uint8_t>(value));
        at = static_cast<size_t>(last - line.data());
        while (at < end && (line[at] == ' ' || line[at] == '\t')) {
            ++at;
        }
        if (at < end && line[at] != ',') {
            fail(path + ":" + std::to_string(line_number) +
                 ": unexpected byte-array separator");
        }
    }
}

Bytes inflate_zlib(const Bytes &input) {
    z_stream stream{};
    stream.next_in = const_cast<Bytef *>(reinterpret_cast<const Bytef *>(input.data()));
    stream.avail_in = static_cast<uInt>(input.size());
    if (static_cast<size_t>(stream.avail_in) != input.size()) {
        fail("zlib input exceeds uInt");
    }
    if (inflateInit(&stream) != Z_OK) {
        fail("inflateInit failed");
    }
    Bytes output;
    constexpr size_t chunk = 256 * 1024;
    int result = Z_OK;
    while (result == Z_OK) {
        const size_t old_size = output.size();
        output.resize(old_size + chunk);
        stream.next_out = reinterpret_cast<Bytef *>(output.data() + old_size);
        stream.avail_out = static_cast<uInt>(chunk);
        result = inflate(&stream, Z_NO_FLUSH);
        output.resize(old_size + chunk - stream.avail_out);
    }
    const bool valid = result == Z_STREAM_END && stream.avail_in == 0;
    inflateEnd(&stream);
    if (!valid) {
        fail("generated array is not one complete zlib stream");
    }
    return output;
}

Bytes deflate_zlib_9(const Bytes &input) {
    const uLong source_size = static_cast<uLong>(input.size());
    if (static_cast<size_t>(source_size) != input.size()) {
        fail("zlib source exceeds uLong");
    }
    Bytes output(compressBound(source_size));
    uLongf output_size = static_cast<uLongf>(output.size());
    const int result = compress2(reinterpret_cast<Bytef *>(output.data()), &output_size,
                                 reinterpret_cast<const Bytef *>(input.data()), source_size, 9);
    if (result != Z_OK) {
        fail("compress2(level=9) failed: " + std::to_string(result));
    }
    output.resize(static_cast<size_t>(output_size));
    return output;
}

Corpus load_corpus(const std::vector<std::string> &paths) {
    Corpus corpus;
    corpus.files = paths;
    for (size_t file_index = 0; file_index < paths.size(); ++file_index) {
        const std::string &path = paths[file_index];
        std::ifstream input(path);
        if (!input) {
            fail("cannot open " + path);
        }
        input.seekg(0, std::ios::end);
        const std::streamoff file_size = input.tellg();
        if (file_size < 0) {
            fail("cannot size " + path);
        }
        corpus.file_bytes.push_back(static_cast<uint64_t>(file_size));
        input.seekg(0, std::ios::beg);
        std::string line;
        size_t line_number = 0;
        bool active = false;
        Blob current;
        while (std::getline(input, line)) {
            ++line_number;
            if (!active) {
                const size_t declaration = line.find("unsigned char ");
                const size_t compressed = line.find("_compressed[]", declaration);
                const size_t brace = line.find('{', compressed);
                if (declaration == std::string::npos || compressed == std::string::npos ||
                    brace == std::string::npos || line.find("_translation_", declaration) == std::string::npos) {
                    continue;
                }
                const size_t name_begin = declaration + std::strlen("unsigned char ");
                current = {};
                current.file_index = file_index;
                current.name = line.substr(name_begin, compressed + std::strlen("_compressed") - name_begin);
                active = true;
                const size_t close = line.find("};", brace + 1);
                parse_values(line, brace + 1, close == std::string::npos ? line.size() : close,
                             current.deflated, path, line_number);
                if (close == std::string::npos) {
                    continue;
                }
            } else {
                const size_t close = line.find("};");
                parse_values(line, 0, close == std::string::npos ? line.size() : close,
                             current.deflated, path, line_number);
                if (close == std::string::npos) {
                    continue;
                }
            }
            if (current.deflated.size() < 4) {
                fail(path + ":" + std::to_string(line_number) + ": empty generated blob");
            }
            current.inflated = inflate_zlib(current.deflated);
            const Bytes regenerated = deflate_zlib_9(current.inflated);
            if (regenerated != current.deflated) {
                fail(path + ":" + std::to_string(line_number) +
                     ": zlib level-9 regeneration is not byte-identical for " + current.name);
            }
            corpus.deflated_bytes += current.deflated.size();
            corpus.inflated_bytes += current.inflated.size();
            corpus.blobs.push_back(std::move(current));
            active = false;
        }
        if (active) {
            fail(path + ": unterminated generated byte array");
        }
    }
    if (corpus.blobs.empty()) {
        fail("no generated translation blobs found");
    }
    return corpus;
}

void configure_zstd(ZSTD_CCtx *context, int level, int window_log) {
    checked_zstd(ZSTD_CCtx_reset(context, ZSTD_reset_session_and_parameters), "ZSTD_CCtx_reset");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_compressionLevel, level),
                 "set compression level");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_windowLog, window_log), "set windowLog");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_enableLongDistanceMatching, 1),
                 "enable long-distance matching");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_checksumFlag, 0), "disable checksum");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_contentSizeFlag, 0),
                 "disable content size");
    checked_zstd(ZSTD_CCtx_setParameter(context, ZSTD_c_dictIDFlag, 0), "disable dictionary id");
}

void append_zstd_stream(ZSTD_CCtx *context, const uint8_t *data, size_t size,
                        ZSTD_EndDirective directive, Bytes &wire) {
    ZSTD_inBuffer input{data, size, 0};
    const size_t chunk = ZSTD_CStreamOutSize();
    do {
        const size_t old_size = wire.size();
        wire.resize(old_size + chunk);
        ZSTD_outBuffer output{wire.data() + old_size, chunk, 0};
        const size_t remaining = checked_zstd(
            ZSTD_compressStream2(context, &output, &input, directive), "ZSTD_compressStream2");
        wire.resize(old_size + output.pos);
        if (input.pos == input.size && remaining == 0) {
            break;
        }
    } while (true);
}

Bytes concatenate(const Corpus &corpus, bool expanded, size_t file_index,
                  bool restrict_file) {
    size_t size = 0;
    for (const Blob &blob : corpus.blobs) {
        if (!restrict_file || blob.file_index == file_index) {
            size += expanded ? blob.inflated.size() : blob.deflated.size();
        }
    }
    Bytes output;
    output.reserve(size);
    for (const Blob &blob : corpus.blobs) {
        if (!restrict_file || blob.file_index == file_index) {
            const Bytes &part = expanded ? blob.inflated : blob.deflated;
            output.insert(output.end(), part.begin(), part.end());
        }
    }
    return output;
}

Bytes encode_whole(const Corpus &corpus, bool expanded, int level, int window_log) {
    const Bytes input = concatenate(corpus, expanded, 0, false);
    ZSTD_CCtx *context = ZSTD_createCCtx();
    if (!context) {
        fail("ZSTD_createCCtx failed");
    }
    configure_zstd(context, level, window_log);
    Bytes output(ZSTD_compressBound(input.size()));
    const size_t size = checked_zstd(
        ZSTD_compress2(context, output.data(), output.size(), input.data(), input.size()),
        "ZSTD_compress2");
    output.resize(size);
    ZSTD_freeCCtx(context);
    return output;
}

Bytes encode_per_file(const Corpus &corpus, bool expanded, int level, int window_log) {
    Bytes output;
    for (size_t file_index = 0; file_index < corpus.files.size(); ++file_index) {
        const Bytes input = concatenate(corpus, expanded, file_index, true);
        ZSTD_CCtx *context = ZSTD_createCCtx();
        if (!context) {
            fail("ZSTD_createCCtx failed");
        }
        configure_zstd(context, level, window_log);
        const size_t old_size = output.size();
        output.resize(old_size + ZSTD_compressBound(input.size()));
        const size_t size = checked_zstd(
            ZSTD_compress2(context, output.data() + old_size, output.size() - old_size,
                           input.data(), input.size()),
            "ZSTD_compress2 per file");
        output.resize(old_size + size);
        ZSTD_freeCCtx(context);
    }
    return output;
}

Bytes encode_persistent_file_flush(const Corpus &corpus, bool expanded, int level,
                                   int window_log) {
    ZSTD_CCtx *context = ZSTD_createCCtx();
    if (!context) {
        fail("ZSTD_createCCtx failed");
    }
    configure_zstd(context, level, window_log);
    Bytes output;
    for (size_t file_index = 0; file_index < corpus.files.size(); ++file_index) {
        const Bytes input = concatenate(corpus, expanded, file_index, true);
        const ZSTD_EndDirective directive =
            file_index + 1 == corpus.files.size() ? ZSTD_e_end : ZSTD_e_flush;
        append_zstd_stream(context, input.data(), input.size(), directive, output);
    }
    ZSTD_freeCCtx(context);
    return output;
}

Bytes encode_per_blob(const Corpus &corpus, bool expanded, int level, int window_log) {
    Bytes output;
    for (const Blob &blob : corpus.blobs) {
        const Bytes &input = expanded ? blob.inflated : blob.deflated;
        ZSTD_CCtx *context = ZSTD_createCCtx();
        if (!context) {
            fail("ZSTD_createCCtx failed");
        }
        configure_zstd(context, level, window_log);
        const size_t old_size = output.size();
        output.resize(old_size + ZSTD_compressBound(input.size()));
        const size_t size = checked_zstd(
            ZSTD_compress2(context, output.data() + old_size, output.size() - old_size,
                           input.data(), input.size()),
            "ZSTD_compress2 per blob");
        output.resize(old_size + size);
        ZSTD_freeCCtx(context);
    }
    return output;
}

Bytes decode_zstd(const Bytes &wire, size_t expected_size) {
    ZSTD_DCtx *context = ZSTD_createDCtx();
    if (!context) {
        fail("ZSTD_createDCtx failed");
    }
    Bytes output(expected_size);
    ZSTD_inBuffer input{wire.data(), wire.size(), 0};
    ZSTD_outBuffer decoded{output.data(), output.size(), 0};
    size_t remaining = 1;
    while (input.pos < input.size || remaining != 0) {
        remaining = checked_zstd(ZSTD_decompressStream(context, &decoded, &input),
                                 "ZSTD_decompressStream");
        if (decoded.pos == decoded.size && (input.pos != input.size || remaining != 0)) {
            ZSTD_freeDCtx(context);
            fail("zstd output exceeds expected size");
        }
        if (input.pos == input.size && remaining != 0) {
            ZSTD_freeDCtx(context);
            fail("truncated zstd stream");
        }
    }
    ZSTD_freeDCtx(context);
    if (decoded.pos != expected_size) {
        fail("zstd output size differs");
    }
    return output;
}

void put_varint(Bytes &out, uint64_t value) {
    while (value >= 128) {
        out.push_back(static_cast<uint8_t>(value) | 128);
        value >>= 7;
    }
    out.push_back(static_cast<uint8_t>(value));
}

size_t metadata_bytes(const Corpus &corpus) {
    Bytes metadata;
    put_varint(metadata, corpus.files.size());
    put_varint(metadata, corpus.blobs.size());
    size_t previous_file = std::numeric_limits<size_t>::max();
    for (const Blob &blob : corpus.blobs) {
        if (blob.file_index != previous_file) {
            put_varint(metadata, blob.file_index);
            previous_file = blob.file_index;
        }
        put_varint(metadata, blob.deflated.size());
        put_varint(metadata, blob.inflated.size());
    }
    return metadata.size();
}

template <typename Function>
std::pair<double, Bytes> best_bytes(int repeats, Function function) {
    double best = std::numeric_limits<double>::infinity();
    Bytes retained;
    for (int run = 0; run < repeats; ++run) {
        const auto begin = Clock::now();
        Bytes result = function();
        const double seconds = std::chrono::duration<double>(Clock::now() - begin).count();
        if (seconds < best) {
            best = seconds;
            retained = std::move(result);
        }
    }
    return {best, std::move(retained)};
}

template <typename Function>
double best_void(int repeats, Function function) {
    double best = std::numeric_limits<double>::infinity();
    for (int run = 0; run < repeats; ++run) {
        const auto begin = Clock::now();
        function();
        best = std::min(best, std::chrono::duration<double>(Clock::now() - begin).count());
    }
    return best;
}

void print_speed(const char *name, double seconds, uint64_t local_bytes,
                 uint64_t raw_corpus_bytes) {
    std::printf("STAGE name=%s seconds=%.6f local_GBps=%.3f effective_raw_GBps=%.3f\n",
                name, seconds, static_cast<double>(local_bytes) / seconds / 1e9,
                static_cast<double>(raw_corpus_bytes) / seconds / 1e9);
}

void benchmark_libdeflate(const Corpus &corpus, int repeats, uint64_t raw_corpus_bytes) {
    LibdeflateApi api;
    if (!api) {
        std::printf("LIBDEFLATE available=no\n");
        return;
    }
    for (int level = 1; level <= 12; ++level) {
        size_t exact_blobs = 0;
        uint64_t exact_deflated = 0;
        uint64_t exact_inflated = 0;
        uint64_t encoded_bytes = 0;
        const double seconds = best_void(repeats, [&] {
            libdeflate_compressor *compressor = api.alloc(level);
            if (!compressor) {
                fail("libdeflate_alloc_compressor failed");
            }
            size_t run_exact_blobs = 0;
            uint64_t run_exact_deflated = 0;
            uint64_t run_exact_inflated = 0;
            uint64_t run_encoded_bytes = 0;
            for (const Blob &blob : corpus.blobs) {
                Bytes encoded(api.bound(compressor, blob.inflated.size()));
                const size_t size = api.compress(compressor, blob.inflated.data(),
                                                 blob.inflated.size(), encoded.data(), encoded.size());
                if (!size) {
                    api.free(compressor);
                    fail("libdeflate_zlib_compress failed");
                }
                encoded.resize(size);
                run_encoded_bytes += size;
                if (encoded == blob.deflated) {
                    ++run_exact_blobs;
                    run_exact_deflated += blob.deflated.size();
                    run_exact_inflated += blob.inflated.size();
                }
            }
            api.free(compressor);
            exact_blobs = run_exact_blobs;
            exact_deflated = run_exact_deflated;
            exact_inflated = run_exact_inflated;
            encoded_bytes = run_encoded_bytes;
        });
        std::printf("LIBDEFLATE level=%d exact_blobs=%zu/%zu exact_deflated=%llu "
                    "exact_inflated=%llu encoded=%llu seconds=%.6f local_GBps=%.3f "
                    "effective_raw_GBps=%.3f\n",
                    level, exact_blobs, corpus.blobs.size(),
                    static_cast<unsigned long long>(exact_deflated),
                    static_cast<unsigned long long>(exact_inflated),
                    static_cast<unsigned long long>(encoded_bytes), seconds,
                    static_cast<double>(corpus.inflated_bytes) / seconds / 1e9,
                    static_cast<double>(raw_corpus_bytes) / seconds / 1e9);
    }
}

void regenerate_blob_range(const Corpus &corpus, size_t file_index, bool restrict_file,
                           unsigned threads) {
    std::vector<size_t> selected;
    for (size_t index = 0; index < corpus.blobs.size(); ++index) {
        if (!restrict_file || corpus.blobs[index].file_index == file_index) {
            selected.push_back(index);
        }
    }
    std::atomic<size_t> next{0};
    std::atomic<bool> mismatch{false};
    std::vector<std::thread> workers;
    workers.reserve(threads);
    for (unsigned worker = 0; worker < threads; ++worker) {
        workers.emplace_back([&] {
            while (true) {
                const size_t position = next.fetch_add(1, std::memory_order_relaxed);
                if (position >= selected.size()) {
                    break;
                }
                const Blob &blob = corpus.blobs[selected[position]];
                if (deflate_zlib_9(blob.inflated) != blob.deflated) {
                    mismatch.store(true, std::memory_order_relaxed);
                }
            }
        });
    }
    for (std::thread &worker : workers) {
        worker.join();
    }
    if (mismatch.load(std::memory_order_relaxed)) {
        fail("parallel zlib regeneration differs");
    }
}

void benchmark_zlib_parallel(const Corpus &corpus, int repeats, uint64_t raw_corpus_bytes) {
    for (unsigned threads : {1U, 2U, 4U, 8U}) {
        const double seconds = best_void(repeats, [&] {
            regenerate_blob_range(corpus, 0, false, threads);
        });
        std::printf("ZLIB_PARALLEL scope=all threads=%u seconds=%.6f local_GBps=%.3f "
                    "effective_raw_GBps=%.3f\n",
                    threads, seconds,
                    static_cast<double>(corpus.inflated_bytes) / seconds / 1e9,
                    static_cast<double>(raw_corpus_bytes) / seconds / 1e9);
    }
    for (size_t file_index = 0; file_index < corpus.files.size(); ++file_index) {
        uint64_t deflated = 0;
        uint64_t inflated = 0;
        size_t blobs = 0;
        for (const Blob &blob : corpus.blobs) {
            if (blob.file_index == file_index) {
                deflated += blob.deflated.size();
                inflated += blob.inflated.size();
                ++blobs;
            }
        }
        for (unsigned threads : {1U, 2U, 4U}) {
            const double seconds = best_void(repeats, [&] {
                regenerate_blob_range(corpus, file_index, true, threads);
            });
            std::printf("ZLIB_PARALLEL scope=tu file=%zu threads=%u blobs=%zu raw=%llu "
                        "deflated=%llu inflated=%llu seconds=%.6f local_GBps=%.3f "
                        "tu_raw_GBps=%.3f\n",
                        file_index, threads, blobs,
                        static_cast<unsigned long long>(corpus.file_bytes[file_index]),
                        static_cast<unsigned long long>(deflated),
                        static_cast<unsigned long long>(inflated), seconds,
                        static_cast<double>(inflated) / seconds / 1e9,
                        static_cast<double>(corpus.file_bytes[file_index]) / seconds / 1e9);
        }
    }
}

using Encoder = Bytes (*)(const Corpus &, bool, int, int);

void run_strategy(const char *name, Encoder encoder, const Corpus &corpus, int level,
                  int window_log, int repeats, uint64_t raw_corpus_bytes,
                  const Bytes &expected_expanded) {
    auto encoded = best_bytes(repeats, [&] { return encoder(corpus, true, level, window_log); });
    auto decoded = best_bytes(repeats, [&] { return decode_zstd(encoded.second, corpus.inflated_bytes); });
    if (decoded.second != expected_expanded) {
        fail(std::string(name) + " decoded payload differs");
    }
    const size_t metadata = metadata_bytes(corpus);
    std::printf("STRATEGY name=%s zstd=%d wire=%zu metadata=%zu charged=%zu encode_s=%.6f "
                "decode_s=%.6f encode_local_GBps=%.3f encode_effective_raw_GBps=%.3f "
                "decode_local_GBps=%.3f decode_effective_raw_GBps=%.3f\n",
                name, level, encoded.second.size(), metadata, encoded.second.size() + metadata,
                encoded.first, decoded.first,
                static_cast<double>(corpus.inflated_bytes) / encoded.first / 1e9,
                static_cast<double>(raw_corpus_bytes) / encoded.first / 1e9,
                static_cast<double>(corpus.inflated_bytes) / decoded.first / 1e9,
                static_cast<double>(raw_corpus_bytes) / decoded.first / 1e9);
}

} // namespace

int main(int argc, char **argv) try {
    uint64_t raw_corpus_bytes = 0;
    int repeats = 3;
    int window_log = 27;
    bool zlib_only = false;
    std::vector<std::string> paths;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--raw-bytes" && i + 1 < argc) {
            raw_corpus_bytes = parse_u64(argv[++i], "--raw-bytes");
        } else if (arg == "--repeat" && i + 1 < argc) {
            repeats = parse_int(argv[++i], "--repeat");
        } else if (arg == "--window-log" && i + 1 < argc) {
            window_log = parse_int(argv[++i], "--window-log");
        } else if (arg == "--zlib-only") {
            zlib_only = true;
        } else if (arg == "--help") {
            std::printf("usage: %s --raw-bytes N [--repeat N] [--window-log N] "
                        "[--zlib-only] FILE...\n",
                        argv[0]);
            return 0;
        } else if (!arg.empty() && arg[0] == '-') {
            fail("unknown option: " + arg);
        } else {
            paths.push_back(arg);
        }
    }
    if (!raw_corpus_bytes || repeats < 1 || paths.empty()) {
        fail("--raw-bytes, a positive --repeat, and at least one FILE are required");
    }

    const auto load_begin = Clock::now();
    const Corpus corpus = load_corpus(paths);
    const double load_seconds = std::chrono::duration<double>(Clock::now() - load_begin).count();
    const Bytes expected_deflated = concatenate(corpus, false, 0, false);
    const Bytes expected_expanded = concatenate(corpus, true, 0, false);

    std::printf("CORPUS files=%zu blobs=%zu deflated=%llu inflated=%llu raw=%llu "
                "metadata=%zu load_s=%.6f zlib=%s zstd=%s\n",
                corpus.files.size(), corpus.blobs.size(),
                static_cast<unsigned long long>(corpus.deflated_bytes),
                static_cast<unsigned long long>(corpus.inflated_bytes),
                static_cast<unsigned long long>(raw_corpus_bytes), metadata_bytes(corpus),
                load_seconds, zlibVersion(), ZSTD_versionString());

    const double inflate_seconds = best_void(repeats, [&] {
        Bytes joined;
        joined.reserve(corpus.inflated_bytes);
        for (const Blob &blob : corpus.blobs) {
            const Bytes value = inflate_zlib(blob.deflated);
            joined.insert(joined.end(), value.begin(), value.end());
        }
        if (joined != expected_expanded) {
            fail("timed inflate differs");
        }
    });
    print_speed("c_inflate", inflate_seconds, corpus.deflated_bytes, raw_corpus_bytes);

    const double deflate_seconds = best_void(repeats, [&] {
        Bytes joined;
        joined.reserve(corpus.deflated_bytes);
        for (const Blob &blob : corpus.blobs) {
            const Bytes value = deflate_zlib_9(blob.inflated);
            joined.insert(joined.end(), value.begin(), value.end());
        }
        if (joined != expected_deflated) {
            fail("timed zlib regeneration differs");
        }
    });
    print_speed("f_deflate9_exact", deflate_seconds, corpus.inflated_bytes,
                raw_corpus_bytes);

    benchmark_zlib_parallel(corpus, repeats, raw_corpus_bytes);

    if (zlib_only) {
        return 0;
    }

    benchmark_libdeflate(corpus, repeats, raw_corpus_bytes);

    for (int level : {1, 3}) {
        const auto baseline = best_bytes(repeats, [&] {
            return encode_whole(corpus, false, level, window_log);
        });
        std::printf("BASELINE name=deflated_whole zstd=%d wire=%zu encode_s=%.6f\n",
                    level, baseline.second.size(), baseline.first);
        run_strategy("expanded_whole", encode_whole, corpus, level, window_log, repeats,
                     raw_corpus_bytes, expected_expanded);
        run_strategy("expanded_per_tu", encode_per_file, corpus, level, window_log, repeats,
                     raw_corpus_bytes, expected_expanded);
        run_strategy("expanded_persistent_tu_flush", encode_persistent_file_flush, corpus,
                     level, window_log, repeats, raw_corpus_bytes, expected_expanded);
        run_strategy("expanded_per_blob", encode_per_blob, corpus, level, window_log, repeats,
                     raw_corpus_bytes, expected_expanded);
    }
    return 0;
} catch (const std::exception &error) {
    std::fprintf(stderr, "compressed_blob_bench: %s\n", error.what());
    return 2;
}
