
sbin_PROGRAMS = icecc-scheduler
icecc_scheduler_SOURCES = connectivityprobe.cpp compileserver.cpp job.cpp jobstat.cpp siblingpin.cpp scheduler.cpp
icecc_scheduler_LDADD = ../services/libicecc.la

AM_LIBTOOLFLAGS = --silent

noinst_HEADERS = \
    connectivityprobe.h \
    compileserver.h \
    job.h \
    jobstat.h \
    scheduler.h \
    selection.h \
    siblingpin.h
